### PR TITLE
fix: health check timeout for services/NLB

### LINKED ISSUE #2898: Service NLB health check timeout annotation is ignored.
**Describe the bug**
When creating a new NLB the health check interval timeout is not used and is set to the same value as the interval. The given timeout is ignored.
**Steps to reproduce**

Create a service with both annotations:
`service.beta.kubernetes.io/aws-load-balancer-healthcheck-interval: "6"`
`service.beta.kubernetes.io/aws-load-balancer-healthcheck-timeout: "2"`

full example: 

```yaml
---
apiVersion: v1
kind: Service
metadata:
  name: testapp
  namespace: lbtest
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: external
    service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: ip
    service.beta.kubernetes.io/aws-load-balancer-ip-address-type: ipv4 # dualstack
    service.beta.kubernetes.io/aws-load-balancer-target-group-attributes: "preserve_client_ip.enabled=true,deregistration_delay.timeout_seconds=60,deregistration_delay.connection_termination.enabled=true"
    service.beta.kubernetes.io/aws-load-balancer-healthcheck-protocol: http
    service.beta.kubernetes.io/aws-load-balancer-healthcheck-port: "8080"
    service.beta.kubernetes.io/aws-load-balancer-healthcheck-path: /healthz
    service.beta.kubernetes.io/aws-load-balancer-healthcheck-healthy-threshold: "2"
    service.beta.kubernetes.io/aws-load-balancer-healthcheck-unhealthy-threshold: "2"
    service.beta.kubernetes.io/aws-load-balancer-healthcheck-interval: "6"
    service.beta.kubernetes.io/aws-load-balancer-healthcheck-timeout: "3"
    service.beta.kubernetes.io/aws-load-balancer-scheme: "internet-facing"
spec:
  selector:
    app: testapp
  ports:
    - name: http
      port: 80
      targetPort: http
    - name: https
      port: 443
      targetPort: https
  type: LoadBalancer
  loadBalancerClass: service.k8s.aws/nlb
```
**Expected outcome**
Targetgroup should have set the timeout to 2

**Environment**

* AWS Load Balancer controller version: v2.4.5
* Kubernetes version : 1.24
* Using EKS (yes/no), if so version? : EKS

**Additional Context**:
relevant logs do not mention the timeout at all
```json
{"level":"info","ts":1669650128.2872295,"logger":"controllers.service","msg":"successfully built model","model":"{\"id\":\"lbtest/testapp\",\"resources\":{\"AWS::ElasticLoadBalancingV2::Listener\":{\"443\":{\"spec\":{\"loadBalancerARN\":{\"$ref\":\"#/resources/AWS::ElasticLoadBalancingV2::LoadBalancer/LoadBalancer/status/loadBalancerARN\"},\"port\":443,\"protocol\":\"TCP\",\"defaultActions\":[{\"type\":\"forward\",\"forwardConfig\":{\"targetGroups\":[{\"targetGroupARN\":{\"$ref\":\"#/resources/AWS::ElasticLoadBalancingV2::TargetGroup/lbtest/testapp:443/status/targetGroupARN\"}}]}}]}},\"80\":{\"spec\":{\"loadBalancerARN\":{\"$ref\":\"#/resources/AWS::ElasticLoadBalancingV2::LoadBalancer/LoadBalancer/status/loadBalancerARN\"},\"port\":80,\"protocol\":\"TCP\",\"defaultActions\":[{\"type\":\"forward\",\"forwardConfig\":{\"targetGroups\":[{\"targetGroupARN\":{\"$ref\":\"#/resources/AWS::ElasticLoadBalancingV2::TargetGroup/lbtest/testapp:80/status/targetGroupARN\"}}]}}]}}},\"AWS::ElasticLoadBalancingV2::LoadBalancer\":{\"LoadBalancer\":{\"spec\":{\"name\":\"k8s-lbtest-testapp-7fe20b9a75\",\"type\":\"network\",\"scheme\":\"internet-facing\",\"ipAddressType\":\"ipv4\",\"subnetMapping\":[{\"subnetID\":\"subnet-064655098f57ab6fe\"},{\"subnetID\":\"subnet-09f79e32b2baab717\"},{\"subnetID\":\"subnet-0b9c5fc0581bc6f58\"}]}}},\"AWS::ElasticLoadBalancingV2::TargetGroup\":{\"lbtest/testapp:443\":{\"spec\":{\"name\":\"k8s-lbtest-testapp-a043ce8c19\",\"targetType\":\"ip\",\"port\":1,\"protocol\":\"TCP\",\"ipAddressType\":\"ipv4\",\"healthCheckConfig\":{\"port\":8080,\"protocol\":\"HTTP\",\"path\":\"/healthz\",\"intervalSeconds\":6,\"healthyThresholdCount\":2,\"unhealthyThresholdCount\":2},\"targetGroupAttributes\":[{\"key\":\"deregistration_delay.connection_termination.enabled\",\"value\":\"true\"},{\"key\":\"deregistration_delay.timeout_seconds\",\"value\":\"60\"},{\"key\":\"preserve_client_ip.enabled\",\"value\":\"true\"},{\"key\":\"proxy_protocol_v2.enabled\",\"value\":\"false\"}]}},\"lbtest/testapp:80\":{\"spec\":{\"name\":\"k8s-lbtest-testapp-48ffc732c6\",\"targetType\":\"ip\",\"port\":1,\"protocol\":\"TCP\",\"ipAddressType\":\"ipv4\",\"healthCheckConfig\":{\"port\":8080,\"protocol\":\"HTTP\",\"path\":\"/healthz\",\"intervalSeconds\":6,\"healthyThresholdCount\":2,\"unhealthyThresholdCount\":2},\"targetGroupAttributes\":[{\"key\":\"deregistration_delay.connection_termination.enabled\",\"value\":\"true\"},{\"key\":\"deregistration_delay.timeout_seconds\",\"value\":\"60\"},{\"key\":\"preserve_client_ip.enabled\",\"value\":\"true\"},{\"key\":\"proxy_protocol_v2.enabled\",\"value\":\"false\"}]}}},\"K8S::ElasticLoadBalancingV2::TargetGroupBinding\":{\"lbtest/testapp:443\":{\"spec\":{\"template\":{\"metadata\":{\"name\":\"k8s-lbtest-testapp-a043ce8c19\",\"namespace\":\"lbtest\",\"creationTimestamp\":null},\"spec\":{\"targetGroupARN\":{\"$ref\":\"#/resources/AWS::ElasticLoadBalancingV2::TargetGroup/lbtest/testapp:443/status/targetGroupARN\"},\"targetType\":\"ip\",\"serviceRef\":{\"name\":\"testapp\",\"port\":443},\"networking\":{\"ingress\":[{\"from\":[{\"ipBlock\":{\"cidr\":\"0.0.0.0/0\"}}],\"ports\":[{\"protocol\":\"TCP\",\"port\":\"https\"}]},{\"from\":[{\"ipBlock\":{\"cidr\":\"10.0.36.0/22\"}},{\"ipBlock\":{\"cidr\":\"10.0.40.0/22\"}},{\"ipBlock\":{\"cidr\":\"10.0.32.0/22\"}}],\"ports\":[{\"protocol\":\"TCP\",\"port\":8080}]}]},\"ipAddressType\":\"ipv4\"}}}},\"lbtest/testapp:80\":{\"spec\":{\"template\":{\"metadata\":{\"name\":\"k8s-lbtest-testapp-48ffc732c6\",\"namespace\":\"lbtest\",\"creationTimestamp\":null},\"spec\":{\"targetGroupARN\":{\"$ref\":\"#/resources/AWS::ElasticLoadBalancingV2::TargetGroup/lbtest/testapp:80/status/targetGroupARN\"},\"targetType\":\"ip\",\"serviceRef\":{\"name\":\"testapp\",\"port\":80},\"networking\":{\"ingress\":[{\"from\":[{\"ipBlock\":{\"cidr\":\"0.0.0.0/0\"}}],\"ports\":[{\"protocol\":\"TCP\",\"port\":\"http\"}]},{\"from\":[{\"ipBlock\":{\"cidr\":\"10.0.36.0/22\"}},{\"ipBlock\":{\"cidr\":\"10.0.40.0/22\"}},{\"ipBlock\":{\"cidr\":\"10.0.32.0/22\"}}],\"ports\":[{\"protocol\":\"TCP\",\"port\":8080}]}]},\"ipAddressType\":\"ipv4\"}}}}}}}"}
{"level":"info","ts":1669650223.1065917,"logger":"controllers.service","msg":"successfully built model","model":"{\"id\":\"lbtest/testapp\",\"resources\":{\"AWS::ElasticLoadBalancingV2::Listener\":{\"443\":{\"spec\":{\"loadBalancerARN\":{\"$ref\":\"#/resources/AWS::ElasticLoadBalancingV2::LoadBalancer/LoadBalancer/status/loadBalancerARN\"},\"port\":443,\"protocol\":\"TCP\",\"defaultActions\":[{\"type\":\"forward\",\"forwardConfig\":{\"targetGroups\":[{\"targetGroupARN\":{\"$ref\":\"#/resources/AWS::ElasticLoadBalancingV2::TargetGroup/lbtest/testapp:443/status/targetGroupARN\"}}]}}]}},\"80\":{\"spec\":{\"loadBalancerARN\":{\"$ref\":\"#/resources/AWS::ElasticLoadBalancingV2::LoadBalancer/LoadBalancer/status/loadBalancerARN\"},\"port\":80,\"protocol\":\"TCP\",\"defaultActions\":[{\"type\":\"forward\",\"forwardConfig\":{\"targetGroups\":[{\"targetGroupARN\":{\"$ref\":\"#/resources/AWS::ElasticLoadBalancingV2::TargetGroup/lbtest/testapp:80/status/targetGroupARN\"}}]}}]}}},\"AWS::ElasticLoadBalancingV2::LoadBalancer\":{\"LoadBalancer\":{\"spec\":{\"name\":\"k8s-lbtest-testapp-7fe20b9a75\",\"type\":\"network\",\"scheme\":\"internet-facing\",\"ipAddressType\":\"ipv4\",\"subnetMapping\":[{\"subnetID\":\"subnet-064655098f57ab6fe\"},{\"subnetID\":\"subnet-09f79e32b2baab717\"},{\"subnetID\":\"subnet-0b9c5fc0581bc6f58\"}]}}},\"AWS::ElasticLoadBalancingV2::TargetGroup\":{\"lbtest/testapp:443\":{\"spec\":{\"name\":\"k8s-lbtest-testapp-a043ce8c19\",\"targetType\":\"ip\",\"port\":1,\"protocol\":\"TCP\",\"ipAddressType\":\"ipv4\",\"healthCheckConfig\":{\"port\":8080,\"protocol\":\"HTTP\",\"path\":\"/healthz\",\"intervalSeconds\":6,\"healthyThresholdCount\":2,\"unhealthyThresholdCount\":2},\"targetGroupAttributes\":[{\"key\":\"deregistration_delay.connection_termination.enabled\",\"value\":\"true\"},{\"key\":\"deregistration_delay.timeout_seconds\",\"value\":\"60\"},{\"key\":\"preserve_client_ip.enabled\",\"value\":\"true\"},{\"key\":\"proxy_protocol_v2.enabled\",\"value\":\"false\"}]}},\"lbtest/testapp:80\":{\"spec\":{\"name\":\"k8s-lbtest-testapp-48ffc732c6\",\"targetType\":\"ip\",\"port\":1,\"protocol\":\"TCP\",\"ipAddressType\":\"ipv4\",\"healthCheckConfig\":{\"port\":8080,\"protocol\":\"HTTP\",\"path\":\"/healthz\",\"intervalSeconds\":6,\"healthyThresholdCount\":2,\"unhealthyThresholdCount\":2},\"targetGroupAttributes\":[{\"key\":\"deregistration_delay.connection_termination.enabled\",\"value\":\"true\"},{\"key\":\"deregistration_delay.timeout_seconds\",\"value\":\"60\"},{\"key\":\"preserve_client_ip.enabled\",\"value\":\"true\"},{\"key\":\"proxy_protocol_v2.enabled\",\"value\":\"false\"}]}}},\"K8S::ElasticLoadBalancingV2::TargetGroupBinding\":{\"lbtest/testapp:443\":{\"spec\":{\"template\":{\"metadata\":{\"name\":\"k8s-lbtest-testapp-a043ce8c19\",\"namespace\":\"lbtest\",\"creationTimestamp\":null},\"spec\":{\"targetGroupARN\":{\"$ref\":\"#/resources/AWS::ElasticLoadBalancingV2::TargetGroup/lbtest/testapp:443/status/targetGroupARN\"},\"targetType\":\"ip\",\"serviceRef\":{\"name\":\"testapp\",\"port\":443},\"networking\":{\"ingress\":[{\"from\":[{\"ipBlock\":{\"cidr\":\"0.0.0.0/0\"}}],\"ports\":[{\"protocol\":\"TCP\",\"port\":\"https\"}]},{\"from\":[{\"ipBlock\":{\"cidr\":\"10.0.36.0/22\"}},{\"ipBlock\":{\"cidr\":\"10.0.40.0/22\"}},{\"ipBlock\":{\"cidr\":\"10.0.32.0/22\"}}],\"ports\":[{\"protocol\":\"TCP\",\"port\":8080}]}]},\"ipAddressType\":\"ipv4\"}}}},\"lbtest/testapp:80\":{\"spec\":{\"template\":{\"metadata\":{\"name\":\"k8s-lbtest-testapp-48ffc732c6\",\"namespace\":\"lbtest\",\"creationTimestamp\":null},\"spec\":{\"targetGroupARN\":{\"$ref\":\"#/resources/AWS::ElasticLoadBalancingV2::TargetGroup/lbtest/testapp:80/status/targetGroupARN\"},\"targetType\":\"ip\",\"serviceRef\":{\"name\":\"testapp\",\"port\":80},\"networking\":{\"ingress\":[{\"from\":[{\"ipBlock\":{\"cidr\":\"0.0.0.0/0\"}}],\"ports\":[{\"protocol\":\"TCP\",\"port\":\"http\"}]},{\"from\":[{\"ipBlock\":{\"cidr\":\"10.0.36.0/22\"}},{\"ipBlock\":{\"cidr\":\"10.0.40.0/22\"}},{\"ipBlock\":{\"cidr\":\"10.0.32.0/22\"}}],\"ports\":[{\"protocol\":\"TCP\",\"port\":8080}]}]},\"ipAddressType\":\"ipv4\"}}}}}}}"}
```

### PR DESCRIPTION
**Pull request by project0**
### Issue

fix #2898

and it solves this error when the interval is set lower:
> {"level":"error","ts":1669717296.2819514,"logger":"controller.service","msg":"Reconciler error","name":nlb","namespace":"app","error":"ValidationError: Health check interval must be greater than the timeout.\n\tstatus code: 400, request id: b2ddcc99-6828-4768-a7c3-ca19ea018291"}

### Description
The annotation for health check timeout was not consumed at all for services, the test have been also wrong.

### Checklist
- [x] Added tests that cover your change (if possible) 
- [ ] Added/modified documentation as required (such as the `README.md`, or the `docs` directory)
- [ ] Manually tested
- [ ] Made sure the title of the PR is a good description that can go into the release notes

### BONUS POINTS checklist: complete for good vibes and maybe prizes?! :exploding_head:
- [ ] Backfilled missing tests for code in same general area :tada:
- [ ] Refactored something and made the world a better place :star2:

### CODE REVIEW

**Comment by kishorj** [comment]
@project0, thanks for your contribution. We ignored the health check timeout earlier due to some limitations on the NLB side. The limitations have now been removed, so we should be able to configure the timeouts as expected. There is still a possibility some regions might not support the new configuration, so I'd recommend to add a feature gate flag set to true by default so we can disable the timeout if support is not available in a certain region.

File: pkg/service/model_build_target_group.go [hunk 1]
```diff
@@ -113,6 +113,10 @@ func (t *defaultModelBuildTask) buildTargetGroupHealthCheckConfigDefault(ctx con
 	if err != nil {
 		return nil, err
 	}
+	healthCheckTimeoutSeconds, err := t.buildTargetGroupHealthCheckTimeoutSeconds(ctx, t.defaultHealthCheckTimeout)
```
Comment (kishorj) [inline pkg/service/model_build_target_group.go:116]: build the timeout based on feature gate. For example, create a new feature gate `NLBHealthCheckTimeout` set to true by default. Refer to the pkg/config/feature_gates.go for more details. 
You can check it as t.featureGates.Enabled(config.NLBHealthCheckTimeout)

Comment (project0) [reply pkg/service/model_build_target_group.go:117]: I named it `ServiceHealthCheckTimeout` to be more consistent with naming.

File: pkg/service/model_build_target_group.go [hunk 2]
```diff
@@ -161,6 +171,7 @@ func (t *defaultModelBuildTask) buildTargetGroupHealthCheckConfigForInstanceMode
 		Protocol:                &healthCheckProtocol,
 		Path:                    healthCheckPathPtr,
 		IntervalSeconds:         &intervalSeconds,
+		TimeoutSeconds:          &healthCheckTimeoutSeconds,
```
Comment (kishorj) [inline pkg/service/model_build_target_group.go:174]: nil ptr if not enabled

File: pkg/service/model_build_target_group.go (hunk 1 above)
Comment (kishorj) [reply pkg/service/model_build_target_group.go:117]: Health check configuration for ALB target groups can also be specified via service annotations, that was the reason I wanted to specifically say NLBHealthCheckTimeout

File: pkg/service/model_build_target_group.go [hunk 3]
```diff
@@ -309,6 +320,9 @@ func (t *defaultModelBuildTask) buildTargetGroupHealthCheckIntervalSeconds(_ con
 }
 
 func (t *defaultModelBuildTask) buildTargetGroupHealthCheckTimeoutSeconds(_ context.Context, defaultHealthCheckTimeout int64) (int64, error) {
+	if !t.featureGates.Enabled(config.ServiceHealthCheckTimeout) {
+		return 0, nil
```
[the remark this answers is not in the document]
Comment (project0) [reply pkg/service/model_build_target_group.go:324]: > 0 is not valid timeout, 

it is the old behavior, default was 0  before as of not set. This is the default behavior with go when you do not use pointers and the json serializer will usually ommit it as empty and not set.

File: pkg/service/model_build_target_group.go (hunk 1 above)
Comment (project0) [reply pkg/service/model_build_target_group.go:117]: > Health check configuration for ALB target groups can also be specified via service annotations, that was the reason I wanted to specifically say NLBHealthCheckTimeout

But the annotation is different: ingress and service: 
`service.beta.kubernetes.io/aws-load-balancer-healthcheck-timeout`
vs 
`alb.ingress.kubernetes.io/healthcheck-timeout-seconds`

File: pkg/service/model_build_target_group.go (hunk 3 above)
[the remark this answers is not in the document]
Comment (project0) [reply pkg/service/model_build_target_group.go:324]: > The feature gate check needs to be done at the calling side

I am not sure what you mean here

File: pkg/service/model_build_target_group.go [hunk 4]
```diff
@@ -126,6 +131,7 @@ func (t *defaultModelBuildTask) buildTargetGroupHealthCheckConfigDefault(ctx con
 		Protocol:                &healthCheckProtocol,
 		Path:                    healthCheckPathPtr,
 		IntervalSeconds:         &intervalSeconds,
+		TimeoutSeconds:          &healthCheckTimeoutSeconds,
```
[the remark this answers is not in the document]
Comment (project0) [reply pkg/service/model_build_target_group.go]: yeah, i missed that when adding the feature gate..

File: pkg/service/model_build_target_group.go (hunk 1 above)
Comment (kishorj) [reply pkg/service/model_build_target_group.go]: You're right, the annotations are different. However, in case of ALB, you could also specify the some of the `alb.ingress.kubernetes.io/*` annotations on a backend service which would affect the particular target group.

File: pkg/service/model_build_target_group.go (hunk 3 above)
[the remark this answers is not in the document]
Comment (kishorj) [reply pkg/service/model_build_target_group.go]: with the *int64 return type, the feature gate check can be done on the function as well. I take back my earlier comments regards to the feature gate check.

**Comment by kishorj** [comment]
@project0, thanks again for your contribution. I will merge the changes once the e2e tests pass.
