### PR TITLE
fix route status reconciler for gw v1.5 upgrade

### LINKED ISSUE #4600: [Gateway API] Error in logs with two parentRefs within one httproute
**Bug Description**
When HTTPRoute has a config with two parentRefs (for example, http and https), there are errors in LBC logs
```
 {"level":"error","ts":"2026-02-24T18:59:32Z","logger":"routeReconciler","msg":"Failed to update route status","error":"HTTPRoute.gateway.networking.k8s.io \"vm-cluster-a-victoria-metrics-cluster-vminsert\" is invalid: [status.parents[1].conditions: Required value, <nil>: Invalid value: \"null\": some validation rules were not checked because the object was invalid; correct the existing errors to complete validation]"}
```

**Steps to Reproduce**
Create HTTPRoute with spec like:
```
spec:
  hostnames:
  - prod-vminsert-vmcluster-a.dummy.domain
  parentRefs:
  - group: gateway.networking.k8s.io
    kind: Gateway
    name: cluster-internal
    namespace: kube-system
    sectionName: https
  - group: gateway.networking.k8s.io
    kind: Gateway
    name: cluster-internal
    namespace: kube-system
    sectionName: http
  rules:
  - backendRefs:
    - group: ""
      kind: Service
      name: vm-cluster-a-victoria-metrics-cluster-vminsert
      port: 8480
      weight: 1
    matches:
    - path:
        type: PathPrefix
        value: /insert
```

**Expected Behavior**
No error log records

**Actual Behavior**
Error in logs. While HTTPRoute works

**Regression**
Not sure. We are on v3.0.0.

**Current Workarounds**
Not sure if this can be counted as a workaround, but removing one parentRef fixes the issue.

**Environment**
- AWS Load Balancer controller version: v3.0.0
- Kubernetes version: 1.34
- Using EKS (yes/no), if so version?: yes, 1.34
- Using Service or Ingress: HTTPRoute
- AWS region: us-east-1
- How was the aws-load-balancer-controller installed: with a helm chart deployed by ArogCD 
- Current state of the Controller configuration:
```
  Containers:
   aws-load-balancer-controller:
    Image:       eks/aws-load-balancer-controller:v3.0.0
    Ports:       9443/TCP, 8080/TCP
    Host Ports:  0/TCP, 0/TCP
    Args:
      --cluster-name=general
      --ingress-class=alb
      --enable-shield=false
      --enable-waf=false
      --enable-wafv2=true
      --enable-backend-security-group=false
      --feature-gates=ALBGatewayAPI=true
```

### PR DESCRIPTION
**Pull request by zac-nixon**
### Issue

https://github.com/kubernetes-sigs/aws-load-balancer-controller/issues/4600

### Description

A couple fixes:
1/ Add a in 'fast unit test' mode which is much faster than standard 'make test.
2/ Fix route reconciler to not operate on route parents outside the scope of the reconcile cycle. This fixes #4600.
3/ Refactor Feature Flags to allow the controller to know if a feature flag was set or it has been defaulted.
4/ Refactor CRD detection logic to use one API call rather than two.

### Checklist
- [x] Added tests that cover your change (if possible)
- [x] Added/modified documentation as required (such as the `README.md`, or the `docs` directory)
- [x] Manually tested
- [x] Made sure the title of the PR is a good description that can go into the release notes

### BONUS POINTS checklist: complete for good vibes and maybe prizes?! :exploding_head:
- [ ] Backfilled missing tests for code in same general area :tada:
- [ ] Refactored something and made the world a better place :star2:

### CODE REVIEW

File: pkg/gateway/crddetect/gateway_feature_flags.go [hunk 1]
```diff
@@ -14,44 +15,74 @@ const (
...
 // disables the corresponding feature flags when required CRDs are missing.
 // It is called from main() after the k8s client is ready and before any
 // controller reads the feature flags.
-func ApplyGatewayCRDDetection(client k8s.DiscoveryClient, featureGates config.FeatureGates, logger logr.Logger) {
-	standardResult := k8s.DetectCRDs(client, GatewayV1GroupVersion, StandardCRDKinds)
-	experimentalResult := k8s.DetectCRDs(client, GatewayV1Alpha2GroupVersion, ExperimentalCRDKinds)
+func ApplyGatewayCRDDetection(client k8s.DiscoveryClient, featureGates config.FeatureGates, logger logr.Logger) error {
 
-	ApplyGatewayFeatureFlags(standardResult, experimentalResult, featureGates, logger)
+	if !featureGates.GetFeatureStatus(config.ALBGatewayAPI).IsDefaulted && !featureGates.GetFeatureStatus(config.NLBGatewayAPI).IsDefaulted {
```
Comment (wweiwei-li) [inline pkg/gateway/crddetect/gateway_feature_flags.go:28]: Q: if a user sets both alb gateway and nlb gateway true,  this line will be true, will do nothing.  What if user set them true but they don't have gateway CRD installed ?

File: pkg/gateway/crddetect/gateway_feature_flags.go [hunk 2]
```diff
@@ -14,44 +15,74 @@ const (
...
+		// User set this flags directly, do nothing.
+		return nil
+	}
+
+	availableResources, err := k8s.DetectCRDs(client, sets.New(GatewayV1Alpha2GroupVersion, GatewayV1GroupVersion, "foo"))
```
Comment (wweiwei-li) [inline pkg/gateway/crddetect/gateway_feature_flags.go]: foo, left over ?

File: pkg/config/feature_gates.go [hunk 3]
```diff
@@ -10,6 +10,11 @@ import (
 
 type Feature string
 
+type FeatureStatus struct {
+	Enabled     bool
+	IsDefaulted bool
```
Comment (wweiwei-li) [inline pkg/config/feature_gates.go:17]: can you add a comment regarding what does IsDefaulted mean, means untouch, or it means currently equal to controller default value

File: pkg/gateway/crddetect/gateway_feature_flags.go (hunk 1 above)
Comment (zac-nixon) [reply pkg/gateway/crddetect/gateway_feature_flags.go:28]: It will crash the controller. I think it is the preferred behavior because the alternative is that you think the Gateway API is enabled when it's really not.

This also helps with installation scenarios where the user had the order wrong. (start controller, then install gateway api crds) as the controller will crash and then pick up that the crds are now installed.

File: pkg/gateway/crddetect/gateway_feature_flags.go (hunk 2 above)
Comment (zac-nixon) [reply pkg/gateway/crddetect/gateway_feature_flags.go]: indeed, sorry. I was testing the logic out.

File: pkg/config/feature_gates.go (hunk 3 above)
Comment (zac-nixon) [reply pkg/config/feature_gates.go:17]: Sure thing.

File: pkg/gateway/crddetect/gateway_feature_flags.go [hunk 4]
```diff
@@ -14,44 +15,74 @@ const (
...
+			if !availableKinds.Has(kind) {
+				missing = append(missing, kind)
+			}
+		}
+	}
+
+	return missing
+}
+
+func generateCombinedRequest(productSpecific map[string][]string, req map[string]sets.Set[string]) {
```
Comment (shuqz) [inline pkg/gateway/crddetect/gateway_feature_flags.go]: where is this function used?

Comment (zac-nixon) [reply pkg/gateway/crddetect/gateway_feature_flags.go]: Left over from old impl. will remove.
